# Generated by Django 4.2.16 on 2025-11-11 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("department_id", models.AutoField(primary_key=True, serialize=False)),
                ("department_name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "departments",
                "ordering": ["department_name"],
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                ("encounter_id", models.AutoField(primary_key=True, serialize=False)),
                ("encounter_date", models.DateTimeField()),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("Office Visit", "Office Visit"),
                            ("Follow-up", "Follow-up"),
                            ("Annual Physical", "Annual Physical"),
                            ("Urgent Care", "Urgent Care"),
                            ("Consultation", "Consultation"),
                            ("Telemedicine", "Telemedicine"),
                            ("Emergency", "Emergency"),
                            ("Procedure", "Procedure"),
                            ("Lab Review", "Lab Review"),
                        ],
                        max_length=100,
                    ),
                ),
                ("chief_complaint", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Checked In", "Checked In"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                            ("No Show", "No Show"),
                        ],
                        default="Scheduled",
                        max_length=50,
                    ),
                ),
                ("clinical_impression", models.TextField(blank=True, null=True)),
                ("treatment_plan", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters",
                        to="healthcare.department",
                    ),
                ),
            ],
            options={
                "db_table": "encounters",
                "ordering": ["-encounter_date"],
            },
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                ("hospital_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hospitals",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ssn",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "insurance_provider",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "patients",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("provider_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("npi", models.CharField(max_length=20, unique=True)),
                ("specialty", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="providers",
                        to="healthcare.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="providers",
                        to="healthcare.hospital",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "providers",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="VitalSign",
            fields=[
                ("vital_signs_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "temperature_value",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "temperature_unit",
                    models.CharField(
                        blank=True,
                        choices=[("C", "Celsius"), ("F", "Fahrenheit")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("blood_pressure_systolic", models.IntegerField(blank=True, null=True)),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(blank=True, null=True),
                ),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                ("respiratory_rate", models.IntegerField(blank=True, null=True)),
                (
                    "oxygen_saturation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        blank=True,
                        choices=[("lbs", "Pounds"), ("kg", "Kilograms")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "height_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "height_unit",
                    models.CharField(
                        blank=True,
                        choices=[("in", "Inches"), ("cm", "Centimeters")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_signs",
                        to="healthcare.encounter",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="healthcare.provider",
                    ),
                ),
            ],
            options={
                "db_table": "vital_signs",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("patient", "Patient"),
                            ("doctor", "Doctor"),
                            ("office_admin", "Office Administrator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="SocialHistory",
            fields=[
                (
                    "social_history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "smoking_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Never", "Never"),
                            ("Former", "Former"),
                            ("Current", "Current"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("alcohol_use", models.CharField(blank=True, max_length=50, null=True)),
                ("drug_use", models.CharField(blank=True, max_length=50, null=True)),
                ("occupation", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("recorded_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_history",
                        to="healthcare.patient",
                    ),
                ),
            ],
            options={
                "db_table": "social_history",
                "ordering": ["-recorded_date"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "prescription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("medication_name", models.CharField(max_length=255)),
                ("dosage", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("route", models.CharField(blank=True, max_length=50, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("refills", models.IntegerField(default=0)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
                (
                    "pharmacy_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "pharmacy_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Discontinued", "Discontinued"),
                            ("Completed", "Completed"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="healthcare.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="healthcare.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="healthcare.provider",
                    ),
                ),
            ],
            options={
                "db_table": "prescriptions",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="primary_doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_patients",
                to="healthcare.provider",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment"),
                            ("lab_result", "Lab Result"),
                            ("prescription", "Prescription"),
                            ("message", "Message"),
                            ("system", "System"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="healthcare.message",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "medical_history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("condition", models.CharField(max_length=255)),
                ("diagnosis_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Resolved", "Resolved"),
                            ("Chronic", "Chronic"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_history",
                        to="healthcare.patient",
                    ),
                ),
            ],
            options={
                "db_table": "medical_history",
                "ordering": ["-diagnosis_date"],
            },
        ),
        migrations.CreateModel(
            name="LabTest",
            fields=[
                ("lab_test_id", models.AutoField(primary_key=True, serialize=False)),
                ("test_name", models.CharField(max_length=255)),
                ("test_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "ordered_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("collection_date", models.DateTimeField(blank=True, null=True)),
                ("result_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ordered", "Ordered"),
                            ("Collected", "Collected"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Ordered",
                        max_length=50,
                    ),
                ),
                ("result", models.TextField(blank=True, null=True)),
                (
                    "result_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("result_unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "reference_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("abnormal_flag", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_tests",
                        to="healthcare.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_tests",
                        to="healthcare.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordered_lab_tests",
                        to="healthcare.provider",
                    ),
                ),
            ],
            options={
                "db_table": "lab_tests",
                "ordering": ["-ordered_date"],
            },
        ),
        migrations.AddField(
            model_name="encounter",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encounters",
                to="healthcare.patient",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encounters",
                to="healthcare.provider",
            ),
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                ("diagnosis_id", models.AutoField(primary_key=True, serialize=False)),
                ("diagnosis_description", models.TextField()),
                ("icd10_code", models.CharField(blank=True, max_length=20, null=True)),
                ("icd11_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "diagnosis_type",
                    models.CharField(
                        choices=[
                            ("Primary", "Primary"),
                            ("Secondary", "Secondary"),
                            ("Differential", "Differential"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Resolved", "Resolved"),
                            ("Rule Out", "Rule Out"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                ("onset_date", models.DateField(blank=True, null=True)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "diagnosed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "diagnosed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="healthcare.provider",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="healthcare.encounter",
                    ),
                ),
            ],
            options={
                "db_table": "diagnoses",
                "ordering": ["-diagnosed_at"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="healthcare.hospital",
            ),
        ),
        migrations.CreateModel(
            name="Allergy",
            fields=[
                ("allergy_id", models.AutoField(primary_key=True, serialize=False)),
                ("allergen", models.CharField(max_length=255)),
                (
                    "allergy_type",
                    models.CharField(
                        choices=[
                            ("Drug", "Drug"),
                            ("Food", "Food"),
                            ("Environmental", "Environmental"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Mild", "Mild"),
                            ("Moderate", "Moderate"),
                            ("Severe", "Severe"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("reaction", models.TextField(blank=True, null=True)),
                ("onset_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="healthcare.patient",
                    ),
                ),
            ],
            options={
                "db_table": "allergies",
                "ordering": ["-severity", "allergen"],
            },
        ),
    ]
