# Generated by Django 4.2.16 on 2025-11-12 02:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyHistory",
            fields=[
                (
                    "family_history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("Father", "Father"),
                            ("Mother", "Mother"),
                            ("Brother", "Brother"),
                            ("Sister", "Sister"),
                            ("Grandfather", "Grandfather"),
                            ("Grandmother", "Grandmother"),
                            ("Uncle", "Uncle"),
                            ("Aunt", "Aunt"),
                            ("Son", "Son"),
                            ("Daughter", "Daughter"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("condition", models.CharField(max_length=255)),
                ("age_at_diagnosis", models.IntegerField(blank=True, null=True)),
                ("is_alive", models.BooleanField(default=True)),
                ("age_at_death", models.IntegerField(blank=True, null=True)),
                (
                    "cause_of_death",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("recorded_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_history",
                        to="healthcare.patient",
                    ),
                ),
            ],
            options={
                "db_table": "family_history",
                "ordering": ["-recorded_date"],
            },
        ),
    ]
