# Generated by Django 4.2.16 on 2025-11-12 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0002_familyhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                ("billing_id", models.AutoField(primary_key=True, serialize=False)),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("billing_date", models.DateField()),
                ("due_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Paid", "Paid"),
                            ("Partial", "Partial"),
                            ("Overdue", "Overdue"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billings",
                        to="healthcare.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billings",
                        to="healthcare.patient",
                    ),
                ),
            ],
            options={
                "db_table": "billings",
                "ordering": ["-billing_date"],
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("doctor", "Doctor"),
                    ("nurse", "Nurse"),
                    ("office_admin", "Office Administrator"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("payment_date", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Credit Card", "Credit Card"),
                            ("Debit Card", "Debit Card"),
                            ("Check", "Check"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Insurance", "Insurance"),
                            ("Other", "Other"),
                        ],
                        default="Cash",
                        max_length=50,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Pending", "Pending"),
                            ("Failed", "Failed"),
                            ("Refunded", "Refunded"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="healthcare.billing",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="healthcare.patient",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceInformation",
            fields=[
                ("insurance_id", models.AutoField(primary_key=True, serialize=False)),
                ("provider_name", models.CharField(max_length=200)),
                ("plan_type", models.CharField(blank=True, max_length=100, null=True)),
                ("policy_number", models.CharField(max_length=100)),
                (
                    "group_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("subscriber_name", models.CharField(max_length=200)),
                (
                    "subscriber_relationship",
                    models.CharField(
                        choices=[
                            ("Self", "Self"),
                            ("Spouse", "Spouse"),
                            ("Parent", "Parent"),
                            ("Child", "Child"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_policies",
                        to="healthcare.patient",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_information",
                "ordering": ["-is_primary", "-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("device_id", models.AutoField(primary_key=True, serialize=False)),
                ("device_unique_id", models.CharField(max_length=255, unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("Watch", "Watch"),
                            ("Ring", "Ring"),
                            ("EarClip", "EarClip"),
                            ("Adapter", "Adapter"),
                            ("PulseGlucometer", "PulseGlucometer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("device_name", models.CharField(max_length=200)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "model_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "firmware_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("capabilities", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Maintenance", "Maintenance"),
                            ("Retired", "Retired"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("battery_level", models.IntegerField(blank=True, null=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("registration_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="healthcare.patient",
                    ),
                ),
            ],
            options={
                "db_table": "devices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillingItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("service_code", models.CharField(max_length=50)),
                ("service_description", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_items",
                        to="healthcare.billing",
                    ),
                ),
            ],
            options={
                "db_table": "billing_items",
                "ordering": ["item_id"],
            },
        ),
    ]
