# Generated by Django 4.2.16 on 2025-11-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0005_officeadministrator"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalsign",
            name="glucose",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=6, null=True
            ),
        ),
    ]
