# Generated by Django 4.2.16 on 2025-11-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0006_vitalsign_glucose"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalsign",
            name="data_source",
            field=models.CharField(
                choices=[("manual", "Manual Entry"), ("device", "IoT Device")],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vitals_recorded",
                to="healthcare.device",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="recorded_by_nurse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_vitals",
                to="healthcare.nurse",
            ),
        ),
    ]
