# Generated by Django 4.2.16 on 2025-11-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0007_vitalsign_data_source_vitalsign_device_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("doctor", "Doctor"),
                    ("nurse", "Nurse"),
                    ("office_admin", "Office Administrator"),
                    ("admin", "System Administrator"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
    ]
